// Minimal ESM bundler: inlines src/ modules into a single _worker.js.
// `cloudflare:sockets` is kept as a static import (Worker runtime provides it).
// Each module is wrapped in its own closure and exposes its exports by name.
import fs from 'fs';
import path from 'path';

const SRC = path.resolve('src');
const OUT = path.resolve('_worker.js');

const EXTERNAL = new Set(['cloudflare:sockets']);
const text = (f) => fs.readFileSync(f, 'utf8');

const mods = [];           // { id, file, source, imports: [{names, dep}] , exports:[], hasDefault }
const index = new Map();   // abs file -> mod
let idc = 0;

function collectExports(src) {
  const names = [];
  let hasDefault = false;
  // export const/let/var NAME = ...
  src = src.replace(/^[ \t]*export\s+(const|let|var)\s+([A-Za-z_$][\w$]*)/gm, (m, kw, name) => { names.push(name); return `${kw} ${name}`; });
  // export function / async function / class NAME
  src = src.replace(/^[ \t]*export\s+(async\s+function|function|class)\s+([A-Za-z_$][\w$]*)/gm, (m, kw, name) => { names.push(name); return `${kw} ${name}`; });
  // export default EXPR;  -> const __default = EXPR;  (must DECLARE it: the
  // bundle is an ESM module, so assigning an undeclared name throws in strict mode)
  src = src.replace(/^[ \t]*export\s+default\s+/gm, () => { hasDefault = true; return 'const __default = '; });
  // export { a, b };  (re-export of local/imported names)
  src = src.replace(/^[ \t]*export\s*\{([^}]*)\}\s*;/gm, (m, inner) => {
    inner.split(',').map((s) => s.trim()).filter(Boolean).forEach((s) => {
      const [local, as] = s.split(/\s+as\s+/);
      names.push(as || local);
    });
    return '';
  });
  // export * (not used)
  return { src, names, hasDefault };
}

function load(file) {
  if (index.has(file)) return index.get(file);
  const mod = { id: 'm' + idc++, file, exports: [], hasDefault: false };
  index.set(file, mod);
  mods.push(mod);
  let src = text(file);
  // imports
  const imports = [];
  src = src.replace(/import\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"]\s*;/g, (m, names, from) => {
    imports.push({ names: names.split(',').map((s) => s.trim()).filter(Boolean), from });
    return '';
  });
  src = src.replace(/import\s*['"]([^'"]+)['"]\s*;/g, (m, from) => { imports.push({ names: [], from }); return ''; });
  mod.imports = imports.map((imp) => {
    if (EXTERNAL.has(imp.from)) return { external: true, names: imp.names };
    const depFile = path.resolve(path.dirname(file), imp.from);
    const dep = load(depFile);
    return { external: false, dep, names: imp.names };
  });
  const { src: cleaned, names, hasDefault } = collectExports(src);
  mod.exports = names;
  mod.hasDefault = hasDefault;
  mod.src = cleaned;
  return mod;
}

const entry = load(path.join(SRC, 'worker.js'));
// post-order: produce the assignment order (deps before dependents)
const ordered = [];
const seen = new Set();
function visit(m) {
  if (seen.has(m.id)) return; seen.add(m.id);
  for (const imp of m.imports) if (!imp.external) visit(imp.dep);
  ordered.push(m);
}
visit(entry);

// build output
let out = '// AUTO-GENERATED by build.js — do not edit.\n';
out += '// Pure-JS OpenVPN TCP client + VLESS WebSocket outbound proxy.\n';
// external imports
const externals = new Set();
for (const m of mods) for (const imp of m.imports) if (imp.external) for (const n of imp.names) externals.add(n);
if (externals.size) out += `import { ${[...externals].join(', ')} } from 'cloudflare:sockets';\n`;
out += '\nconst __ns = {};\n';
for (const m of ordered) {
  let src = m.src;
  // rewrite imports to namespace lookups
  for (const imp of m.imports) {
    if (imp.external) continue; // names come from the static import at top
    const local = imp.names.map((n) => { const [a, b] = n.split(/\s+as\s+/); return b ? `${a}: ${b}` : a; }).join(', ');
    src = `const { ${local} } = __ns[${JSON.stringify(imp.dep.id)}];\n` + src;
  }
  const retNames = [...m.exports, ...(m.hasDefault ? ['__default'] : [])].join(', ');
  out += `const ${m.id} = (() => {\n${src}\nreturn { ${retNames} };\n})();\n__ns[${JSON.stringify(m.id)}] = ${m.id};\n`;
}
out += `export default __ns[${JSON.stringify(entry.id)}].__default;\n`;

fs.writeFileSync(OUT, out, 'utf8');
console.log('bundled', mods.length, 'modules -> _worker.js (' + out.length + ' bytes)');